### ISSUE TITLE
Inconsistent validation errors

### ISSUE THREAD

**Issue by pokhiii** [goyalujjwal8/E-library#5]
The validation error styles on the registration page is different from the login page

![image](https://user-images.githubusercontent.com/11808845/113830249-0f2d7480-97a4-11eb-9fd8-f8bb0875ab64.png)

![image](https://user-images.githubusercontent.com/11808845/113830113-e60ce400-97a3-11eb-992b-71a25d8e99b3.png)

**Comment by goyalujjwal8** [comment]
this is becoz on registration page validation are backend...and on login page validation are frontend.... will fix this asap
