### ISSUE TITLE
Description box of Book detail page

### ISSUE THREAD

**Issue by Anupam-Panwar** [goyalujjwal8/E-library#6]
User is able to add content in description box in Book detail page(though it is not getting saved)
I think it is because of the textbox that you have used for description box
![image](https://user-images.githubusercontent.com/65714751/114052154-69652d00-98ab-11eb-9141-925277cf7483.png)

**Comment by goyalujjwal8** [comment]
yeah, it is coz of the textbox... cool i'll fix this
