### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by gaurish-saini** [goyalujjwal8/E-library#7]
![image](https://user-images.githubusercontent.com/58362095/113847456-2163de80-97b5-11eb-9bac-d46512ea6bd5.png)

![image](https://user-images.githubusercontent.com/58362095/114032259-c526ba80-9899-11eb-9b6c-78eb1aed2bf6.png)

**Comment by gaurish-saini** [comment]
![image](https://user-images.githubusercontent.com/58362095/115694197-43955900-a37e-11eb-9bcd-f6c7f218a063.png)
I think the issue still persist. let me know if I am unclear.

**Comment by goyalujjwal8** [comment]
sorry Gaurish as it was simple for me to change my homepage to login page but I did not like it that way so  I let my homepage like this only, Hope you did not mind for not considering the change....

**Comment by gaurish-saini** [comment]
> sorry Gaurish as it was simple for me to change my homepage to login page but I did not like it that way so I let my homepage like this only, Hope you did not mind for not considering the change....

I just mentioned it because I saw requirements were violated, rest is up to you.
