### ISSUE TITLE
multiple reading book

### ISSUE THREAD

**Issue by aman-coder** [goyalujjwal8/E-library#8]
![prep2](https://user-images.githubusercontent.com/55488429/113849935-92a49100-97b7-11eb-898a-c3dd55645360.jpg)
![Preparatory Exercise – 2 - Google Docs - Google Chrome 4_7_2021 3_38_24 PM](https://user-images.githubusercontent.com/55488429/113849989-a18b4380-97b7-11eb-94c2-f596cd5ac7e6.png)

**Comment by goyalujjwal8** [comment]
Thank u for finding out this data redundancy will fix this soon...

**Comment by mohitgusain** [comment]
@goyalujjwal8  can you add some padding inside the box. The content is looking a bit off inside the box

**Comment by goyalujjwal8** [comment]
@mohitgusain will do that sir...
